application:
  port: 8000
  hmac_secret: "very-long-and-very-secret-random-key-to-verify-message-integrity"

database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"

email_client:
#  base_url: "https://api.postmarkapp.com"
  base_url: "localhost"
  sender_email: "pierre@grompiler.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000
